---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность переключить язык интерфейса.
  
non-functional: 
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт нужно протестировать на совместимость с последними версиями браузеров.
  - Важно, чтобы сайт мог обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь локализацию (перевод) на русский и английский языки.
  
implicit:
  - Интерфейс сайта должен иметь адаптивный дизайн и быть интуитивно понятным для любого пользователя.
  - Отфильтрованные товары должны запоминаться системой даже после обновления страницы.
  - У пользователя не должно быть возможности ввести отрицательную цену товара.
  - Оформление заказа должно быть недоступным при пустой корзине.
  - При слабом интернет соединении, должна выводится основная информация магазина.
  - После оформления заказа, должна появиться возможность перехода на страницу оплаты.
  - Мобильная версия сайта должна корректно отображать весь контент.
  - Должна присутствовать защита от XSS.
  - Личные данные пользователя должны быть защищены, - корзина и окно оплаты не должны быть видны другим пользователем.
  - Нельзя положить товар в корзину, если его нет в наличии.
  - Нельзя оформить заказ, если товара нет в наличии.
